# .github/workflows/azure-deploy.yml
name: Build & Deploy Front-end
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3           # Node 20 satisfies react-router 7
        with: { node-version: '20' }

      - name: Build
        working-directory: frontend
        run: |
          npm ci
          npm run build                       # → frontend/dist/…

      - name: Zip build output
        run: |
          cd frontend/dist
          zip -r ../../site.zip .

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: tarrifs-frontend-app
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: site.zip
          startup-command: 'pm2 serve /home/site/wwwroot --spa --no-daemon'
